language: node_js

node_js:
  - "10"
  - "12"
  - "14"

env:
  - SERVERLESS_VERSION=latest COV_PUB=true DEPLOY=true

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:build

after_success: test -z "$COV_PUB" || npm run coverage

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true
