language: node_js
node_js: ["6"]

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:build

after_success: test -z true || npm run coverage

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true
